/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        ChangePwdModal: typeof import('./src/components/ChangePwdModal.vue')['default']
        PageBox: typeof import('./src/components/PageBox.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}

// For TSX support
declare global {
    const ChangePwdModal: typeof import('./src/components/ChangePwdModal.vue')['default']
    const PageBox: typeof import('./src/components/PageBox.vue')['default']
    const RouterLink: typeof import('vue-router')['RouterLink']
    const RouterView: typeof import('vue-router')['RouterView']
}