/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangePwdModal: typeof import('./src/components/ChangePwdModal.vue')['default']
    PageBox: typeof import('./src/components/PageBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TEnhancedTable: typeof import('tdesign-vue-next')['EnhancedTable']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuGroup: typeof import('tdesign-vue-next')['MenuGroup']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTree: typeof import('tdesign-vue-next')['Tree']
    TTreeSelect: typeof import('tdesign-vue-next')['TreeSelect']
    TTypographyText: typeof import('tdesign-vue-next')['Text']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}

// For TSX support
declare global {
  const ChangePwdModal: typeof import('./src/components/ChangePwdModal.vue')['default']
  const PageBox: typeof import('./src/components/PageBox.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TAvatar: typeof import('tdesign-vue-next')['Avatar']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDialog: typeof import('tdesign-vue-next')['Dialog']
  const TDrawer: typeof import('tdesign-vue-next')['Drawer']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TEnhancedTable: typeof import('tdesign-vue-next')['EnhancedTable']
  const TForm: typeof import('tdesign-vue-next')['Form']
  const TFormItem: typeof import('tdesign-vue-next')['FormItem']
  const THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLink: typeof import('tdesign-vue-next')['Link']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuGroup: typeof import('tdesign-vue-next')['MenuGroup']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TOption: typeof import('tdesign-vue-next')['Option']
  const TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
  const TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSpace: typeof import('tdesign-vue-next')['Space']
  const TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const TTree: typeof import('tdesign-vue-next')['Tree']
  const TTreeSelect: typeof import('tdesign-vue-next')['TreeSelect']
  const TTypographyText: typeof import('tdesign-vue-next')['Text']
  const TUpload: typeof import('tdesign-vue-next')['Upload']
}